# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      issues: write
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore unit-test-poc.sln
    - name: Build
      run: dotnet build unit-test-poc.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test unit-test-poc.sln  --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --logger trx --results-directory coverage
    - name: Copy Coverage To Predictable Location
      run: cp coverage/*/coverage.cobertura.xml coverage/coverage.cobertura.xml
    - name: Create code coverage report
      run: |
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator -reports:coverage/coverage.cobertura.xml -targetdir:CodeCoverage -reporttypes:'Html;lcov;MarkdownSummaryGithub;Cobertura'
    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/coverage.cobertura.xml
        badge: true
        fail_below_min: false
        format: markdown
        hide_branch_rate: false
        hide_complexity: false
        indicators: true
        output: both

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md  
    - uses: romeovs/lcov-reporter-action@v0.2.16
      with:
        lcov-file: CodeCoverage/lcov.info
    - name: Produce the coverage report and comment
      uses: insightsengineering/coverage-action@v2
      with:
        path: coverage/coverage.cobertura.xml
        threshold: 80.123
        fail: false
        publish: true
        diff: true
        diff-branch: main
        diff-storage: _xml_coverage_reports
    - uses: 5monkeys/cobertura-action@master
      name: An Additional Commenting option
      with:
        path: coverage/coverage.cobertura.xml
        link_missing_lines: true
        show_missing: true
        show_line: true
        show_branch: true
        show_class_names: true
